# Use root/example as user/password credentials
version: '3.9'

services:
  mongo:
    image: mongo:5.0.6-focal
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mysql:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB
    ports:
      - "3306:3306"
    volumes:
      - demo_mysql_data:/var/lib/mysql

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Admin UI (http://localhost:15672  .. admin:admin)
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  demo_mysql_data:
  mongodb_data:
